server:
  port: 8081

spring:
  application:
    name: class-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: class_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
